title: "Welcome to Business Programming (MGT 3745)!"
theme: jekyll-theme-minimal
description: >
  Life is short (You need Python) - Bruce Eckel
logo: "https://raw.githubusercontent.com/jonathanatuscpsu/Business-Programming/main/Python_66.png"
show_downloads: false

github:
  is_project_page: false

color_mode:
  default: auto   # auto | light | dark
  toggle: true

sass:
  style: compressed
