title: "Welcome to Business Programming (MGT 3745)!"
theme: jekyll-theme-minimal

description: >
Life is short (You need Python) - Bruce Eckel

logo: "https://github.com/jonathanatuscpsu/Business-Programming/raw/gh-pages/python.jpg"
show_downloads: false

github:
  is_project_page: false
