title: "Welcome to Business Programming (MGT 3745)!"
theme: jekyll-theme-cayman
description: "By Zhaohu (Jonathan) Fan <br /> ''Life is short (You need Python).'' ---Bruce Eckel"
github:
  is_project_page: false
