title: "Welcome to Business Programming (MGT 3745)!"
theme: jekyll-theme-minimal

description: >
  Teaching materials for data mining and business analytics courses.

logo: "https://github.com/jonathanatuscpsu/DM-python/raw/gh-pages/DM.jpg"
show_downloads: false

github:
  is_project_page: false
